Part4
MasonSelf/PFMCPP_Project5 pull request #4
Opened 2020-10-25 16:00 UTC by MasonSelf

2020-10-25 16:49 UTC, matkatmusic requested changes

2020-10-25 16:49 UTC, matkatmusic commented on Wrappers.h
> +
You aren't using anything from these in this header file so you don't need to include them.
Forward Declare
- [ ] revise

2020-10-25 20:11 UTC, MasonSelf commented on Wrappers.h
> +
I forward declared these. I'm now getting "new line required at end of file" warnings that I can't resolve by adding lines

2020-10-27 06:22 UTC, matkatmusic approved these changes

2020-10-27 06:22 UTC, merged